### ISSUE TITLE
Combine the Back-end and Front-end language files

### ISSUE THREAD

**Issue by ocean123** [Equotix/Logic-Invoice#10]
Hi,

Wouuw, beautiful software. Works like a charm.

Is it posible to combine the admin and user language files. That is easier to translate. Now there are double translations rows. For example $_['text_biennally'] we have to translate it in the back-end en front-end. 

Double work... I don't like double work :-/

Best regards
Ocean

**Comment by EsmondTan** [comment]
This sounds like a great idea, something we will look into in the next release.
