### ISSUE TITLE
Missing items catalog for invoices

### ISSUE THREAD

**Issue by zamolxe** [Equotix/Logic-Invoice#11]
Stumbled on this piece of software recently and decided to give it a try. I can say that it's looking promising, but there are few things missing.
Currently there is no catalog for invoice items, eg. products, services, etc.
It's kind of annoying to always type the same text and prices for several invoices if the items is the same for all of them.

**Comment by EsmondTan** [comment]
This will be an upcoming feature. It's exactly how we're feeling right now when we've to enter the same details repeatedly.

**Comment by blmg911** [comment]
I agree completely, this shows awesome potential.

Love the fact it is modelled on Opencart's system, which is a simple system to use and development add ons for. 

However I believe the core functions such as the one mentioned above needs to be improved well before you launch a marketplace or anything along theses lines.

**Comment by EsmondTan** [comment]
Feature added for next release: 68b50edee30bc8e5adae1684a28f0ff2629cdd3b
