### ISSUE TITLE
Installer Assets Issues ++ Running full SSL everywhere

### ISSUE THREAD

**Issue by dhaupin** [Equotix/Logic-Invoice#13]
Do you have plans to allow full SSL everywhere? I have done some work with OC and OC2 regarding this. The most annoying part is the installer and trying to use forced SSL + HSTS...it blocks all the assets for the page(s). I don't wanna start on a mod/pull if you guys are already working on it, but if not, lemme know

**Comment by EsmondTan** [comment]
@dhaupin by full SSL, do you mean to put the whole website loading 'https'? If so, all you need to do is to add https to the config files where you the URLs. That should do the job.

**Comment by dhaupin** [comment]
Yes it will sort of, but it still calls assets and dynamic links as http and has other quirks such as using images in WYSIWYG as relative src, or not forcing `link()` method without `SSL` arg to rewrite https. Or in the case of Cloudflare or other proxies/CDN, it doesn't understand what to look at as far as https mode goes both in install and post install. As far as the install steps go, there is no config written yet to grab post-install config, so the relative paths of the ajax requests (tpl) need `$application` defined in each function (controller) based on a more thorough https switch before constants in install/index.php (and rewriting the swtich in startup.php), which also adds `$_SERVER['PROTOCOL']` for use in mode switch within HTTP_APPLICATION installer constant. Hope that makes sense. I think i got it figured out, but xmas hit hah. I can do a pullski later this week maybe

**Comment by EsmondTan** [comment]
@dhaupin no problem, if you can propose a pull request we can have a look at it again.
