### ISSUE TITLE
Email Template text placeholders

### ISSUE THREAD

**Issue by willbarraclough** [Equotix/Logic-Invoice#14]
Hi, I am new to Logic Invoice, and upon setup, have found that when emails are generated, the shortcodes aren't functioning properly.

What seems to be the case is where { } is used, the system doesn't acknowledge the brackets { }, instead just the word.

For example, if I created a new customer with the following credentials,
     Name: Pear Shaped
     Password: Banana2016

the email reads:
"
     Welcome to {My Company}

     Hi {Pear Shaped},

     Welcome to {My Company}. You may login to your account by clicking here.

     Your Banana2016 is {Banana2016}.

     Regards,
     {My Company}
"
• Notice how all the { } are still in place, and where it should say Your password is Banana2016, the system has seen the work 'password' and replaced it with Your Banana2016 is {Banana2016}

**Comment by EsmondTan** [comment]
Hi there,

This may help you: 96ab194174458a4f621e0d077f6abf25ae451cb5.
We've already resolved the issue and it's available in the commits, but not yet released.
