### ISSUE TITLE
Issues with Journal Entries

### ISSUE THREAD

**Issue by mjbrancato** [Equotix/Logic-Invoice#15]
No matter how you try to track your expenses or deposits I always get
"Debit and credit needs to be equal."

If this is the case, then you would never be able to track money going and and out.

**Comment by EsmondTan** [comment]
@mjbrancato are your debit & credit values equal in one single journal entry transaction? See example below.

![capture](https://cloud.githubusercontent.com/assets/12963207/13811687/6a1cbde0-ebb2-11e5-8b74-7983db0e59e7.JPG)

**Comment by paulohsrocha** [comment]
i also do not understand it. can you explain best?

**Comment by EsmondTan** [comment]
if there's anything, use the forum for discussion. this is only used for reporting valid bugs. @paulohsrocha
