### ISSUE TITLE
Cant select from Select Dropdown 

### ISSUE THREAD

**Issue by bestamit** [Equotix/Logic-Invoice#16]
Hi , this is fantastic app .
there are some bugs like while i select customer from customer dropdown while creating invoice , it shows dropdown but when i click on it , it doesnt work.
The selection is not working

**Comment by EsmondTan** [comment]
@bestamit Are you able to take a screenshot or a video of it? That may be easier for us to track down the issue

**Comment by bestamit** [comment]
try creating recurring invoice , and select customer from dropdown , it wont reflect
