### ISSUE TITLE
Bug Change Theme

### ISSUE THREAD

**Issue by paulohsrocha** [Equotix/Logic-Invoice#19]
I can not change the theme, after the change in administration the site remains in default theme in logicinvoice 1.1.1 .
How to solve?

**Comment by EsmondTan** [comment]
unable to replicate the issue on our end. We cloned a test theme folder and we can switch to a different theme. Do let us know how to replicate it.

**Comment by paulohsrocha** [comment]
So, I also copy a test theme folder and I can't switch to a different theme. The system stay in default theme. =/

**Comment by paulohsrocha** [comment]
Sorted out. Sorry, I forgot to change the line of the stylesheet with the way my css file. Grateful!
