### ISSUE TITLE
New language refresh

### ISSUE THREAD

**Issue by hellkingvrh** [Equotix/Logic-Invoice#25]
So today I was translating this awesome invoice system my local language and found out that after I change the language in setting changes are not instantly visible. I had to delete cookies to see changes. I tried to find where is the problem in code but I haven't any luck so maybe somebody else can find it.

**Comment by EsmondTan** [comment]
The system stores a cache of the language last selected. We will be working on a language changing interface on the front end in the next release as well and that should resolve the issue.

**Comment by EsmondTan** [comment]
https://github.com/Equotix/Logic-Invoice/commit/49585dc842e858b49c0a9831a0a175383341c514

Fixes the admin side to only have the default admin language used. Further improvements to front end will be made down the road.
