### ISSUE TITLE
The Quantity of Products is not getting reduced from the Inventory 

### ISSUE THREAD

**Issue by LogicoWise** [Equotix/Logic-Invoice#28]
Hello There,

if we add few items in Invoice and save it, the inventory is not getting updated and quantity is not getting reduced with the added quantity in a invoice.

**Comment by EsmondTan** [comment]
Right now the invoice doesn't deduct inventory, we will be looking into improvements in the next release for this.

**Comment by crazyshaitan** [comment]
Any idea by when you will have next release with product subtraction feature ?

**Comment by LogicoWise** [comment]
Hello All,

I have done some changes in my local copy , its DB level changes which does this functionality.  Shall I share this?

**Comment by crazyshaitan** [comment]
Sure. Please share . email : narang.gourav@gmail.com

Thanks

**Comment by beipink** [comment]
Best way is to send a pull request here. So your work can be verified by the community for integration with the application.

**Comment by paulohsrocha** [comment]
Hello guys!

About "if we add few items in Invoice and save it, the inventory is not
getting updated and quantity is not getting reduced with the added quantity
in a invoice."...

I believe that Logic Invoice don't was produced for this. In this case we
should developer a order page, integrated at a product catalog.

I avaiable to do this!

:)

Paulo Henrique Rocha
Desenvolvedor Web
(31)98282-0460

Em 14/10/2016 09:11, "beipink" <notifications@github.com> escreveu:

**Comment by EsmondTan** [comment]
Logic Invoice isn't an ordering / shopping cart. It's built to be an accounting system + invoicing system. We will look into improving inventory management in the next few releases

**Comment by paulohsrocha** [comment]
Yes! Exactly this I wanted say.
But if someone want do this, I can help.

Thanks!

Paulo Henrique Rocha
Desenvolvedor Web
(31)98282-0460

Em 14/10/2016 11:18, "Esmond" <notifications@github.com> escreveu:

**Comment by Uzenmi** [comment]
@EsmondTan: You need have an option "Unlimited" for quantity of items (example, if admin type "0" in to the quantity field mean is unlimited).

**Comment by ganyram** [comment]
@LogicoWise please share the same, gany.akshu@gmail.com. thank you. Looking forward for this feature.
