### ISSUE TITLE
The pagination is not working

### ISSUE THREAD

**Issue by paulohsrocha** [Equotix/Logic-Invoice#29]

**Comment by paulohsrocha** [comment]
When I click on the next page button it go to wrong address. For example, on blog:
http://logicinvoice/content/blog?page=%7page%7D

Do you see this problem or can be just with me?

**Comment by EsmondTan** [comment]
I don't see any blog pagination on our current blog system. Do you have an online system with the issue or a screenshot?

**Comment by paulohsrocha** [comment]
The pagination configured in System > Settings > Website > Website List Limit.
I entry 1 for test, and when I access Blog, Invoices or other page with pagination, apper this problem.
See on https://drive.google.com/file/d/0B5hBrhinxFWKTTh4SzQ5aFp2RU0/view?usp=docslist_api

**Comment by EsmondTan** [comment]
Just tested by adding more blog posts and it seems to paginate correctly. No issues with it. Tested on live demo: http://demo.logicinvoice.com/index.php?load=content/blog&page=1
