### ISSUE TITLE
Ticket extension

### ISSUE THREAD

**Issue by Uzenmi** [Equotix/Logic-Invoice#31]
Can I install [this ticket extension](https://www.opencart.com/index.php?route=extension/extension/info&extension_id=26704&filter_search=ticket&sort=e.price&order=ASC&page=1) to Logic?  Thanks.

**Comment by EsmondTan** [comment]
Definitely not.

**Comment by Uzenmi** [comment]
So do you have plan to develop ticket module? I think it so important to support customers.

**Comment by EsmondTan** [comment]
Discussion can be done through our forums. No plans for any ticketing system at the moment. There are plenty of great services out there such as Zendesk or Freshdesk.
