### ISSUE TITLE
 Fatal error: Call to undefined function imagecreatefrompng() in C:\Apache24\htdocs\LogicInvoice2\system\library\image.php on line 32

### ISSUE THREAD

**Issue by vikram-bodige** [Equotix/Logic-Invoice#36]
Hi 
i have successfully installed LogicInvoice and able to login from admin page. but while opening settings, i am getting error. Please help me out to resolve the issue.

Fatal error: Call to undefined function imagecreatefrompng() in C:\Apache24\htdocs\LogicInvoice2\system\library\image.php on line 32

**Comment by EsmondTan** [comment]
install gd library for php. that should solve your issue. if you require further assistance, do use our forum.

**Comment by vikram-bodige** [comment]
Yes, Resolved, Thanks alot..!!
