### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by mgazelle** [Equotix/Logic-Invoice#38]
after a successful installation, the system keeps sending me back to the login page with correct credentials. With wrong credentials I get the login page with an error message as expected.
If I disable the preactions Login and Permission checks I can see the dashboard.
I could not find the code to redirect to the dashboard after a successful authentication.
Any Help?

**Comment by paulohsrocha** [comment]
Show more details of your problem with prints and error log file.

Maybe I can help you.

Paulo Henrique Rocha
(31)98425-8624

Em 07/06/2017 20:18, "Mongi Gazelle" <notifications@github.com> escreveu:

**Comment by EsmondTan** [comment]
It's likely a session handling issue. Do open a topic in the forum for support.
