### ISSUE TITLE
Quotation does not link to Journal Entries

### ISSUE THREAD

**Issue by Uzenmi** [Equotix/Logic-Invoice#48]
I can not get link from Quotation to Journal Entries.

**Comment by Uzenmi** [comment]
Change show error = 1 then you can see the error.

**Comment by EsmondTan** [comment]
Quotation is not yet released, we are still working on it.

**Comment by Uzenmi** [comment]
The error in local test:

[https://imgur.com/Xe0I0At](https://imgur.com/Xe0I0At)

[https://imgur.com/nqiZYdc](https://imgur.com/nqiZYdc)

[https://imgur.com/ieUDLMn](https://imgur.com/ieUDLMn)
